# These are just dummy objects
# If you want to use own objects, create and load an own apriltag and object yaml file

# Defenitions of training objects
# object type is one of CUBE, SPHERE, CYLIINDER, MESH
# tag size is defined in apriltags yaml
objects:
  - object:
      name: "table_lab_large"
      type: CUBE
      tag_id: 17
      scale: {x: 1.6, y: 0.8, z: 0.68}
      # tag offset
      origin: [-0.71, -0.31, -0.34] # half the table width/length - 90mm tag center
      rpy: [0.0, 0.0, -0.00]
#      tags: [18, 19, 20]
  - object:
      name: "table_ur5"
      type: CUBE
      tag_id: 42
      scale: {x: 1.0, y: 0.8, z: 0.74}
      # tag offset
      origin: [0.0, 0.0, -0.068]
      rpy: [0.0, 0.0, 0.0]
#      tags: [18, 19, 20]
  - object:
      name: "table_trixi"
      type: CUBE
      tag_id: 21
      scale: {x: 1.0, y: 0.8, z: 0.74}
      # tag offset
      origin: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
#      tags: [21, 22, 23, 24]
  - object:
      name: "continente coffee"
      type: CUBE
      tag_id: 110
      scale: {x: 0.06, y: 0.06, z: 0.136}
      # tag offset
      origin: [0.0, 0.0, -0.068]
      rpy: [0.0, 0.0, 0.0]
#      tags: [111, 112, 113, 114]
  - object:
      name: "dummy"
      type: CUBE
      tag_id: 115
      scale: {x: 0.05, y: 0.05, z: 0.05}
      # tag offset
      origin: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
#      tags: [116, 117, 118, 119]
  - object:
      name: "dummy2"
      type: CUBE
      tag_id: 120
      scale: {x: 0.05, y: 0.05, z: 0.05}
      # tag offset
      origin: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
  - object:
      name: "piece_of_wood"
      type: CUBE
      tag_id: 130
      scale: {x: 0.057, y: 0.0395, z: 0.1225} # not sure if this is the correct order
      # tag offset should be 0 as this is a bundle tag and the offset should be set correctly in the apriltags.yaml
      origin: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
#      tags: [131, 132, 133, 134]
#  - object:
#      type: MESH
#      mesh: '<path_to_mesh>'
#      tags: [41, 42, 43]
#      scale: {x: 0.1, y: 0.1, z: 0.1}
